In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4]

In [3]:
print(lst)

[1, 2, 3, 4]


In [ ]:
np.random.

In [5]:
np.array(lst)

array([1, 2, 3, 4])

In [10]:
mat = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [17]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.linspace(1,11,25) 

array([ 1.        ,  1.41666667,  1.83333333,  2.25      ,  2.66666667,
        3.08333333,  3.5       ,  3.91666667,  4.33333333,  4.75      ,
        5.16666667,  5.58333333,  6.        ,  6.41666667,  6.83333333,
        7.25      ,  7.66666667,  8.08333333,  8.5       ,  8.91666667,
        9.33333333,  9.75      , 10.16666667, 10.58333333, 11.        ])

In [13]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [14]:
np.random.rand(4)

array([0.81148769, 0.44049325, 0.52048035, 0.31726801])

In [15]:
np.random.rand(4,5)

array([[0.95387316, 0.80309394, 0.18577283, 0.87726253, 0.91252825],
       [0.09358641, 0.95685956, 0.66541472, 0.57361782, 0.49427694],
       [0.76142252, 0.85237847, 0.32489534, 0.91007093, 0.89738902],
       [0.34953449, 0.4318021 , 0.74352394, 0.59336548, 0.62779646]])

In [16]:
np.random.rand(5,5)

array([[0.91403671, 0.11029574, 0.25564042, 0.82913195, 0.03178352],
       [0.08052595, 0.05193498, 0.90141722, 0.7756288 , 0.4163855 ],
       [0.70614486, 0.02853393, 0.19738278, 0.73494211, 0.69000036],
       [0.81265104, 0.255132  , 0.24747555, 0.03555642, 0.29563983],
       [0.81439426, 0.96775496, 0.6943542 , 0.55385755, 0.02648184]])

In [17]:
np.random.rand(2)

array([0.54809778, 0.58616164])

In [20]:
np.random.randint(4)

2

In [21]:
np.random.randint(4,7)

5

In [23]:
np.random.randint(7,30,5)

array([28, 24, 23, 15, 25])

In [21]:
#Reshape
a = np.arange(25)

In [25]:
r = np.random.randint(0,50,10)

In [23]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
a.shape

(25,)

In [25]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
# max:
a.max()

24

In [27]:
#min:
a.min()

0

In [32]:
r.argmax()

2

In [33]:
r

array([11,  7, 45, 27, 27, 31,  9, 25, 15, 39])

In [30]:
a.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [31]:
a.shape

(25,)

In [32]:
a.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [33]:
a.shape

(25,)

In [34]:
#dtype for show its type:
a.dtype

dtype('int32')

In [38]:
x = [4,56,9.0]

In [40]:
x = np.array(x)

In [41]:
x.dtype

dtype('float64')

In [42]:
#  Numpy Indexing and Seletion
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
a = np.arange(11)

In [44]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
a[2]

2

In [46]:
a[:5]

array([0, 1, 2, 3, 4])

In [47]:
a[0:5] = 1000

In [48]:
a

array([1000, 1000, 1000, 1000, 1000,    5,    6,    7,    8,    9,   10])

In [56]:
a = np.arange(11)

In [50]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
s = a[0:5]

In [52]:
s

array([0, 1, 2, 3, 4])

In [53]:
#replace:
s[:] = 777

In [54]:
s

array([777, 777, 777, 777, 777])

In [55]:
a

array([777, 777, 777, 777, 777,   5,   6,   7,   8,   9,  10])

In [57]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
#dot copy function
s = a[0:5].copy()

In [59]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
s

array([0, 1, 2, 3, 4])

In [63]:
s[:] = 333

In [64]:
s

array([333, 333, 333, 333, 333])

In [65]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
mat2 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
               ])

In [73]:
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
mat2.shape

(3, 3)

In [75]:
mat2[1]

array([4, 5, 6])

In [76]:
mat2[1][1]

5

In [77]:
mat2[1,1]

5

In [78]:
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
mat2[1:,1:]

array([[5, 6],
       [8, 9]])

In [81]:
mat2[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [83]:
b = np.arange(1,11)

In [84]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
b > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [86]:
#Selection:
b[b>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
b[b == 2]

array([2])

In [89]:
b[b <= 2]

array([1, 2])

In [94]:
# Arithmetic:
c = np.arange(0,11)

In [91]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
c + c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [93]:
c * c

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [95]:
c/c

D:\Users\A1063477\AppData\Local\Temp\ipykernel_8656\2321899886.py:1: RuntimeWarning: invalid value encountered in divide
  c/c


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [96]:
1/c

D:\Users\A1063477\AppData\Local\Temp\ipykernel_8656\1004997379.py:1: RuntimeWarning: divide by zero encountered in divide
  1/c


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [97]:
c ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [98]:
np.sqrt(c)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [99]:
np.exp(c)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [100]:
np.max(c)

10

In [101]:
np.log(c)

D:\Users\A1063477\AppData\Local\Temp\ipykernel_8656\2051865075.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(c)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [102]:
mat2 * mat2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [103]:
mat2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])